# order-service.yml 파일 내용 수정
eureka:
  client:
    enabled: false          # 유레카 끄기
    fetch-registry: false
    register-with-eureka: false

feign:
  client:
    config:
      catalog-service:
        url: http://catalog-service:8082
      user-service:
        url: http://user-service:8081
      key-inventory-service:
        url: http://key-inventory-service:8085