spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
gateway:
  ip: 192.168.219.100
  server:
    webflux:
      routes:
        # 유저 서비스 Actuator
        - id: user-service-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # 유저 서비스
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/info/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: userLoginCircuitBreaker
                fallbackUri: forward:/fallback/login-service
        # 유저 포인트 증감/차감
        - id: user-service-point
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/point/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # 회원가입
        - id: user-service-register
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # 로그인
        - id: user-service-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20000
                redis-rate-limiter.burstCapacity: 40000
            - name: CircuitBreaker
              args:
                name: userLoginCircuitBreaker
                fallbackUri: forward:/fallback/login-service

        # 제품 서비스 Actuator
        - id: catalog-service-actuator
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/actuator/**
          filters:
            - RewritePath=/catalog-service/(?<segment>.*), /$\{segment}
        # 제품 서비스
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        # 주문 서비스 Actuator
        - id: order-service-actuator
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/actuator/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        # 주문 서비스
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - AuthorizationHeaderFilter
        # 게임 키 서비스 Actuator
        - id: key-inventory-service-actuator
          uri: lb://KEY-INVENTORY-SERVICE
          predicates:
            - Path=/key-inventory/actuator/**
          filters:
            - RewritePath=/key-inventory/(?<segment>.*), /$\{segment}
        # 게임 키 서비스 (인증 제외)
        - id: key-inventory-keys-public
          uri: lb://KEY-INVENTORY-SERVICE
          predicates:
            - Path=/key-inventory/keys
            - Method=GET
        # 게임 키 서비스
        - id: key-inventory-service
          uri: lb://KEY-INVENTORY-SERVICE
          predicates:
            - Path=/key-inventory/**
          filters:
            - AuthorizationHeaderFilter
        # 결제 서비스 Actuator
        - id: pay-service-actuator
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/actuator/**
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
        # 결제 서비스
        - id: pay-service-process
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/payment/success, /payment-service/payment/cancel, /payment-service/payment/fail
        # 결제 서비스
        - id: pay-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - AuthorizationHeaderFilter
        # 장바구니 서비스 Actuator
        - id: order-service-cart-actuator
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cart-service/actuator/**
          filters:
            - RewritePath=/cart-service/(?<segment>.*), /$\{segment}
        # 장바구니 서비스
        - id: order-service-cart
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cart-service/**
          filters:
            - AuthorizationHeaderFilter
        # 찜하기 서비스 Actuator
        - id: user-service-wish-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/wish-service/actuator/**
          filters:
            - RewritePath=/wish-service/(?<segment>.*), /$\{segment}
        # 찜하기 서비스
        - id: user-service-wish
          uri: lb://USER-SERVICE
          predicates:
            - Path=/wish-service/**
          filters:
            - AuthorizationHeaderFilter
        # 토큰 재발급
        - id: user-service-refresh
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/refresh
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - httpexchanges
          - busrefresh
          - prometheus
          - metrics

resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 1000
        maxWaitDuration: 2s
    instances:
      userLoginCircuitBreaker:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        failureRateThreshold: 60
        waitDurationInOpenState: 10s
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s