spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gameinfo_pay
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    config:
      name: gameinfo,kakao-service
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_id_generator_strategy_three_lo: false
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - busrefresh
          - prometheus
          - metrics