spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AYA6S8nVD+swGNCDWyw+n7yavuMAhi03pnLHN5sFzAN9rmwo7MHN3dC+2nxINZuEoimAtna9VVSaFFvQwY1BOen0EoPz8WEpuucMg6AXxxTjdbjahlV2xaapmmzAB8fjJqf8fvYD/6Ay90FfLYYhFlrVg7CPB/9pnf9w60plWQ+AKYHbCSRJ80HNRxKbLqGh/ZJqPDdOJ8FtKUhrxDwml1jeYg3gy1HrTMV1//VPqxWWDM7gfy24nEBZ4LcQrCs5u/YuPX48/utVDTNpOA12lCk5s0U8jT6Gr609EShBQd8PYolNnAI2QU/4P+Fz6y1DD4JP8bEyKpNEZWhjMmx85jIMa2hZPN52a39ZMl8nea+osscAmxUeW0QiLpTbK/h2VdRWWvGIwi/LlBSF2FZSiYOVBDRcbjEOXVFdcVXT0fybo6N3MDOtnuFcBnpVHNDHUHW4q4OPjNEtfysu903onOcNWDjd5GVlLWJ6eu3VjNwYPWRBph1m62vQrTpsn/I0WrtkjyqtwOxLpQ0AHLuK6+R8isfUQKAOzbt+MsvIaI0wfA=='

  token:
    secret: '{cipher}AYAlWdVoY3PNf2/7OnNPK/UwkPbJUFeKCqbdTM4RjhEItfxNiqqF8260ZvnCZV9nyWCKDoMxmMXMA/U+XACY897J6x2Wr89n1p3dg31EcSfpvIX0NCVH4NFWIDF2eEyxQxvOOJDT0ZSn9bhwZDCnMVUkFCfPJ3cdnvWXKiR87FHeW5g+GDuG+hnw9JegNPNZN7cnIJGG9AeDhSD84czvjxbgeLSrBxjGkMGF0kGq3rnIOFP7F7Gmz75d6bYSOc0Ik4gsuAAba32n8hqIBAEYrzD7jQwYJYUiKrtTpEh+LSgf/kzr8p1TUx6cyfvxYQeioXnTo0QFGY/1afwuiOIQhuiwC/IbDV+JKhTBaKOjF3uauluH4GLP7/1QuE9iBdnvgvvgr2hOH/d9bqg1mliUZF9OIlM7gOmqxbvP+owhIjxySj+fegMwAF3WbPm6lc1XuQ1X0JDFHGc1iAxWkyGHrmd2t0TDGD/DIJnzoOKQNRpLIY2GV4Sfe60qXdrDwVkmftxmYX0WCVJyZp6VNeenAInPybZAjetOXW1Np2Es8PdpV1UvSiJMS3qq0WPOfPi7xfTYhclRyRGbCAlpC4r8DejeiPP3k6sxxHy7d1LQ29FUZxV3PGpgTcJq8P8dwnMqMeY='
    access-token:
      expiration-time: 1800000 # 30 minutes
    refresh-token:
      expiration-time: 864000000 # 10 days